[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
tag_format = "v$version"
version_files = [
    "setup.py:version",
    ".cz.toml:version",
    "docs/conf.py:version",
]
update_changelog_on_bump = true
