default_stages:
  - commit
exclude: docs|.git|.tox
fail_fast: true
repos:
  - hooks:
      - id: commitizen
        stages: [ commit-msg ]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1

  - hooks:
      - id: detect-secrets
        args: [ '--baseline', '.pre-commit/.secrets.baseline' ]
        exclude: (docs|README.md)
    repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.4.0

  - hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        files: \.(json)$
      - id: check-toml
        files: \.(toml)$
      - id: check-yaml
        files: \.(yaml)$
      - id: fix-encoding-pragma
        args: [ --remove ]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0

  - hooks:
      - id: isort
        entry: isort --settings-path=.pre-commit
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1

  - hooks:
      - exclude: (/settings/)
        id: black
        args:
          - --config=.pre-commit/pyproject.toml
        language_version: python3.8
        require_serial: true
        types:
          - python
    repo: https://github.com/ambv/black
    rev: 23.1.0

  - hooks:
      - args:
          - --config=.pre-commit/setup.cfg
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 6.0.0

  - hooks:
      - entry: pylint --rcfile=.pre-commit/.pylintrc
        files: \.py$
        id: system
        language: system
        name: PyLint
    repo: local

  - hooks:
      - id: bandit
        args: [ --verbose, -ll, --recursive, . ]
    repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
